### ISSUE TITLE
All builds of the new MacOS packages are broken

### ISSUE THREAD

**Issue by chobberoni** [daily-demos/daily-launcher#2]
@markbackman and 
- I tested this in realtime and the arm64 pkg shows up as corrupted.
- The intel package is super duper slow and doesn't run the meeting
- The windows package is flawless. 

Example https://daily-video-launcher.s3.us-west-2.amazonaws.com/daily-video-1.0.0-mac-arm64.dmg

**Thoughts:**
- Maybe something changed in the binaries when the new repo was created.
- I just retested this with my local build (fresh) on my arm64 device and it worked flawlessly.

**Comment by lazeratops** [comment]
This is related to code signing being required to run binaries on a Mac other than the machine they were built on. I've requested help internally to get these signed with whoever has access to Apple's Developer Program (or advise on whether it's possible to sign development builds without ADP certs)
